baseURL = 'https://www.yangzhenfei.com'
languageCode = 'zh-cn'
title = 'Seeking Complexity'
theme = 'smol'
refLinksErrorLevel = "WARNING"
relativeURLs = true

[sitemap]
  filename = 'sitemap.xml'

[[module.mounts]]
  source = 'static/ox-hugo'
  target = 'assets/ox-hugo'

[markup.goldmark.renderer]
  unsafe= true

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2

